### ISSUE TITLE
Spelling corrections

### ISSUE THREAD

**Issue by carygravel** [PhilterPaper/Perl-PDF-Builder#125]
PDF::Builder::Content resemblence->resemblance
PDF::Builder::Content hypenation->hyphenation
PDF::Builder::Docs convertable->convertible

**Comment by PhilterPaper** [comment]
Oh my. And I thought that _I_ was anal about spelling and grammar glitches! Corrected and in the library. I plead "typo" on the second, but "guilty" on the first and third, Your Honor.

Seriously, if you find more spelling or grammar problems, feel free to re-open this ticket and pile 'em on. Thank you!
