### ISSUE TITLE
Errors when using 3.021 with text() after having previously used a version in 2017.

### ISSUE THREAD

**Issue by risner** [PhilterPaper/Perl-PDF-Builder#145]
my $text = $page->text();
   $text->font($bask, 6);
   $text->translate(32, 30);
   $text->text('Small Parts' , { color => 'black' });

That code results in this error now:
Reference found where even-sized list expected at /Users/risner/perl5/lib/perl5/PDF/Builder/Content.pm line 3451, <> line 3.

Perl 5.32

There are other errors the code is reporting:
Reference found where even-sized list expected at /Users/risner/perl5/lib/perl5/PDF/Builder/Content.pm line 3230.
Odd number of elements in hash assignment at /Users/risner/perl5/lib/perl5/PDF/Builder/Content.pm line 3451.

Of note, the output is correct. The text is draw at the spot expected, as expected. Well as far as I can tell.

**Comment by PhilterPaper** [comment]
I don't think you're using correct Perl syntax here.

`$text->text('Small Parts' , -indent => 18,  -underline => 'auto'  );`

Colors cannot be set here as an option. You need to use something like the `fillcolor('black')` method.

**Comment by PhilterPaper** [comment]
I have just released version 3.022. With no further comment from the OP, I'll assume that I can close this ticket now.
