### ISSUE TITLE
TIFF+Alpha

### ISSUE THREAD

**Issue by carygravel** [PhilterPaper/Perl-PDF-Builder#154]
Here's a new way of breaking the alpha code in TIFF:

`magick convert -depth 1 -size 2x2 pattern:gray50 -scale 1000% -alpha on TIFF/alpha/2.tif`

**Comment by PhilterPaper** [comment]
What is this supposed to produce? Windows PhotoViewer refuses to display it (says it's corrupted). Windows Photo and Windows Paint say it's an unsupported format, GIMP shows a 20x20 image with no content, just the checkerboard "transparent" background. ImageMagick IMDisplay shows a 2x2 checkerboard (4 squares).

I tried again with `magick convert -depth 1 -size 20x20 pattern:gray50 -alpha on TIFF/alpha/3.tif`. Again, Windows won't display it, and GIMP shows no content. IMDisplay shows a 20x20 B&W checkerboard.

I just want to make sure I understand what it's _supposed_ to be, before I spend time running it through PDF::Builder.

**Comment by carygravel** [comment]
As you say, it produces a 2x2 chessboard.

I was looking for smaller images IM could create on the fly to speed up the tests and that wouldn't create so much output when they fail.

I'm guessing the corruption in Builder is due to something like a requirement that the row length be a whole number of bytes.

**Comment by carygravel** [comment]
It looks as though at least some of the inversion problems might be specific to LZW:

```
magick convert -depth 1 -gravity center -pointsize 78 -size 1000x100 caption:\"A caption for the image\" -compress lzw out.tif
```

**Comment by PhilterPaper** [comment]
Do you mean LZW _without_ alpha layer? So might this be one of those edge-case problems you mentioned with LZW-to-Flate compression messing up things? Your example with and without LZW displays fine with ImageMagick (although Windows Photo Viewer says they're both corrupt). PDF::Buillder shows the LZW-compressed inverted and no compression OK (black on white).

**Comment by PhilterPaper** [comment]
Current status:
  
- 2.tif and 3.tif (unscaled) both display an _empty_ PDF image, with a warning message from Acrobat Reader that the PDF is corrupted. Firefox and XpdfReader show a corrupted image (not a checkerboard).
- out.tif and outNoComp.tif (uncompressed) both seem to display OK (black on white).
- G4.tiff still fails to display on Acrobat Reader.
