### ISSUE TITLE
GT no longer recognised since PR 156 style cleanup, etc.

### ISSUE THREAD

**Issue by carygravel** [PhilterPaper/Perl-PDF-Builder#159]
In current master, GT is no longer recognised, and all tests that require it are skipped. I've git bisected the commit that introduced the problem, and it seems to have happened here:

```
bc55017c3f8e7f5d08a9792b29903695034e4849 is the first bad commit
commit bc55017c3f8e7f5d08a9792b29903695034e4849
Author: Phil Perry <phil4597@catskilltech.com>
Date:   Sat Apr 17 22:43:11 2021 -0400

    PR 156 style cleanup, etc.

 Changes                                            |  11 +-
 Makefile.PL                                        |   2 +-
 lib/PDF/Builder.pm                                 |   2 +-
 lib/PDF/Builder/Basic/PDF/Filter/LZWDecode.pm      | 228 ++++++++++++++++++---
 lib/PDF/Builder/Resource/XObject/Image/TIFF.pm     |  95 +++------
 .../Builder/Resource/XObject/Image/TIFF/File.pm    |   4 +-
 .../Builder/Resource/XObject/Image/TIFF/File_GT.pm |   4 +-
 lib/PDF/Builder/Resource/XObject/Image/TIFF_GT.pm  | 184 ++++++++++-------
 t/00-all-usable.t                                  |   2 +-
 t/filter-lzwdecode.t                               |  75 +++++++
 t/tiff.t                                           | 121 ++++++++++-
 11 files changed, 548 insertions(+), 180 deletions(-)
 create mode 100644 t/filter-lzwdecode.t
```

**Comment by PhilterPaper** [comment]
Are you saying that the tests which claim to use GT are actually _not_ using it? I'm confused. It's certainly _not_ skipping the t-tests with a message to that effect.

**Comment by carygravel** [comment]
No. I'm saying that the `$tiff->usesLib()` test for GT stopped working after that commit, so that where normally, I see:
`
ok 1 - '$pdf->image_tiff(filename)' isa 'PDF::Builder::Resource::XObject::Image::TIFF_GT'
`

I now see see

`
ok 1 - '$pdf->image_tiff(filename)' isa 'PDF::Builder::Resource::XObject::Image::TIFF'
`

and all the tests that require GT are skipped.

**Comment by carygravel** [comment]
I think I've found the problem - I hadn't updated GT to 10 everywhere, because the bug causing the update to 10 didn't occur on my systems. I assume that updating GT will fix the problem. Sorry for the noise.

**Comment by carygravel** [comment]
Confirmed. Please close this.
