### ISSUE TITLE
Distorted text in PDFs created with browsers

### ISSUE THREAD

**Issue by Tekki** [PhilterPaper/Perl-PDF-Builder#168]
PDF::Builder 3.022, Perl 5.34.0 on Debian

If text is added to a PDF created with one of the following browsers it appears distorted (wrong size, mirrored):
- Chrome
- Brave
- Edge

Not affected: Firefox.

How to reproduce:
- open page `about:blank`
- print the page as PDF to 'download.pdf'
- run the following script

```perl
#!/usr/bin/env perl
use strict;
use warnings;

use PDF::Builder;

my $file = $ARGV[0] || 'download.pdf';

my $pdf  = PDF::Builder->open($file);
my $page = $pdf->openpage(1);

my $font = $pdf->corefont('Helvetica-Bold');
my $text = $page->text();
$text->font($font, 12);
$text->translate(200, 200);
$text->text('Abcde');

$pdf->saveas("stamped_$file");
```

**Comment by PhilterPaper** [comment]
This sounds like it's a known issue with the Chrome engine. In certain circumstances, such as adding headers and footers to a page, it sets up the coordinate system vertically reversed (0 at top, about 3300 units high). Unfortunately, it leaves the coordinate system in this state, so anything you add to it will be mirrored. The solution is to add a PDF command to your text stream to reset the coordinate system to the standard orientation and size.

See in the POD for "Content" a discussion of using `$content->add()` to add a `cm` command to fix the scaling and orientation. Let me know if it does the job for you.

**Comment by Tekki** [comment]
To add the sample code from the [Content.pm docs](https://metacpan.org/pod/PDF::Builder::Content#$content-%3Eadd(@content))  definitely solves my issue. I found a second case in PDFs with producer 'Microsoft: Print To PDF', where the scale has to be set to approximately 0.75.
Thanks a lot for your feedback and your help!
