### ISSUE TITLE
optional_update.pl is installed

### ISSUE THREAD

**Issue by ppisar** [PhilterPaper/Perl-PDF-Builder#169]
PDF-Builder-3.023 added ./optional_update.pl script. That file is unexpectedly installed with "make install" command. The reason is that the file ends with ".pl" and resides in a root directory <https://metacpan.org/pod/ExtUtils::MakeMaker#PM>. You either need to patch Makefile.PL to exclude it, or move the file somewhere else (./tools?), or rename it.

**Comment by PhilterPaper** [comment]
That installation behavior always catches me! I'll look into updating the program to work from within tools/, and move it there. It's only used by developers who have installed the ancillary parts of the package, and is not used for basic operation.

**Comment by PhilterPaper** [comment]
I have moved it to tools/. It should be run as tools/optional_update.pl, so that it knows where to find the files it wants to update. Thanks for alerting me.

You may of course remove optional_update.pl from your Perl run time library, if it got installed there.
