### ISSUE TITLE
Ghostscript 9.55 has broken the full windows test

### ISSUE THREAD

**Issue by carygravel** [PhilterPaper/Perl-PDF-Builder#172]
Compare

https://github.com/carygravel/Perl-PDF-Builder/runs/3868694017?check_suite_focus=true

with

https://github.com/PhilterPaper/Perl-PDF-Builder/runs/3724125995?check_suite_focus=true

I'll see if I can fix this in the next couple of days.

**Comment by PhilterPaper** [comment]
I guess you can close this ticket at your convenience. The test.yml update listed as running correctly.
