### ISSUE TITLE
ChordPro: t/8*_pages.t fail on some systems

### ISSUE THREAD

**Issue by ChordPro** [PhilterPaper/Perl-PDF-Builder#190]
Please see https://github.com/ChordPro/chordpro/issues/256 .

**Comment by PhilterPaper** [comment]
Need to add a guard in the `page()` method to warn and treat an out-of-range new page number as a "reasonable" value (to avoid a splice() warning).

**Comment by PhilterPaper** [comment]
Checks added to keep the new page number in range. Will appear in the next release (3.025), hopefully by the end of the year.
