### ISSUE TITLE
ttfont uninitialized value in hash warning message

### ISSUE THREAD

**Issue by PhilterPaper** [PhilterPaper/Perl-PDF-Builder#205]
In PDF::API2 ticket ssimms/pdfapi2/issues/71, @svenoe reports receiving warning messages that 3 out of 256 entries are uninitialized in a specific font:

-----------------------------------
When calling ttfont() on a PDF::API2 object with -encoding => 'utf-8', I receive a warning three times. Unfortunately I understand neither the aim of the code here, nor pack and decode well enough, to say much more.
```
use PDF::API2;
print "Version: $PDF::API2::VERSION\n";

my $pdf = PDF::API2->new();
$pdf->addFontDirs('var/fonts'); # some font containing directory

my $font = $pdf->ttfont('DejaVuSansMono.ttf', '-encode', 'utf-8');
```
> Version: 2.045
> Use of uninitialized value in hash element at /usr/local/share/perl/5.26.1/PDF/API2/Resource/CIDFont.pm line 290.
> Use of uninitialized value in hash element at /usr/local/share/perl/5.26.1/PDF/API2/Resource/CIDFont.pm line 290.
> Use of uninitialized value in hash element at /usr/local/share/perl/5.26.1/PDF/API2/Resource/CIDFont.pm line 290.

This comes from

[pdfapi2/lib/PDF/API2/Resource/CIDFont.pm](https://github.com/ssimms/pdfapi2/blob/1b998771a82aab35cd633e9ad57f9020dfaea83c/lib/PDF/API2/Resource/CIDFont.pm#L276)

Line 276 in [1b99877](https://github.com/ssimms/pdfapi2/commit/1b998771a82aab35cd633e9ad57f9020dfaea83c)
`unpack('U*', decode($enc, pack('C*', 0 .. 255))) `
only returning 253 instead of 256 strings, and thus the line above mapping (253..255) onto undef.

Old versions (at least 2.033-old) had a no warnings qw[ deprecated recursion uninitialized ]; in the code, so I assume that this is maybe no error. And map { unpack( 'U*', decode( $enc, pack( 'C*', $_ ) ) ) } (0..255) would do something which looks similar in outcome (to me^^), but doesn't have the gaps, but that is, as said before, just guess work...

Thanks in any case and best regards, Sven

-----------------------------------
I was unable to replicate this problem on PDF::Builder, and was hoping that Sven might have tried it in PDF::Builder, or at least have more information to share. I am not permitted to post to PDF::API2, so I can't talk to you there. I have been waiting to see if there has been any progress on this, but there doesn't appear to have been any.

In the path to the font, is `var/fonts` a directory _relative_ to either the current directory (your program is running in), or to some fixed base directory? I was wondering if it should be `/var/fonts` (absolute, not relative, path). Following the instructions above, I have not had any error messages, but I'm also running under Windows. I _do_ have that font, under `\Windows\fonts`. Is there any way for you to verify that your copy of the font file has not been corrupted?

**Comment by svenoe** [comment]
Hi @PhilterPaper,

thanks for replying - I can replicate it for PDF::Builder, but while writing this and trying to boil things down, I noticed that it only happens in one of my environments, so maybe it's the perl version. First quickly, it's not the fonts directory, you can even leave that out, I noticed:

```
#!/usr/bin/perl
use warnings;

use PDF::Builder;
print "perl $^V\nBuilder: $PDF::Builder::VERSION\n";

my $pdf = PDF::Builder->new();

my $font = $pdf->ttfont('DejaVuSansMono.ttf', '-encode', 'utf-8');
```

returns
```
perl v5.26.1
Builder: 3.026
Use of uninitialized value in hash element at pdfbuilder/lib/perl5/PDF/Builder/Resource/CIDFont.pm line 358.
Use of uninitialized value in hash element at pdfbuilder/lib/perl5/PDF/Builder/Resource/CIDFont.pm line 358.
Use of uninitialized value in hash element at pdfbuilder/lib/perl5/PDF/Builder/Resource/CIDFont.pm line 358.
```

And now more specifically:
```
#!/usr/bin/perl
use warnings;
use Encode qw(:all);

print "perl $^V\n";

my $enc = 'utf-8';

my $e2u = [
    map { ($_ and $_>0x7f and $_<0xA0)? uniByName(nameByUni($_)): $_ }
    unpack('U*', decode($enc, pack('C*', 0..255)))
];

my %u2e;
foreach my $n (reverse 0..255) {
    $u2e{$e2u->[$n]} //= $n;
}

print "done\n";
```

returns on an older server:
```
perl v5.26.1
Use of uninitialized value in hash element at x line 16.
Use of uninitialized value in hash element at x line 16.
Use of uninitialized value in hash element at x line 16.
done
```

but no warning on my laptop:
```
perl v5.30.3
done
```

This can, as written in the other thread be tracked down to the following:
```
#!/usr/bin/perl
use warnings;
use Encode qw(:all);

print "perl $^V\n";

my $enc = 'utf-8';

my @pdu = unpack('U*', decode($enc, pack('C*', 0..255)));
for ( reverse 0..255 ) { printf "%3d - %s\n", $_, ( $pdu[$_] // 'undef' ) };
```

Resulting in (and only differing in the first three entries):
```
perl v5.26.1
255 - undef
254 - undef
253 - undef
252 - 65533
251 - 65533
250 - 65533
249 - 65533
248 - 65533
247 - 65533
246 - 65533
245 - 65533
244 - 65533
243 - 65533
242 - 65533
241 - 65533
240 - 65533
239 - 65533
238 - 65533
237 - 65533
236 - 65533
235 - 65533
234 - 65533
233 - 65533
232 - 65533
231 - 65533
230 - 65533
229 - 65533
228 - 65533
227 - 65533
226 - 65533
225 - 65533
224 - 65533
223 - 65533
222 - 65533
221 - 65533
220 - 65533
219 - 65533
218 - 65533
217 - 65533
216 - 65533
215 - 65533
214 - 65533
213 - 65533
212 - 65533
211 - 65533
210 - 65533
209 - 65533
208 - 65533
207 - 65533
206 - 65533
205 - 65533
204 - 65533
203 - 65533
202 - 65533
201 - 65533
200 - 65533
199 - 65533
198 - 65533
197 - 65533
196 - 65533
195 - 65533
194 - 65533
193 - 65533
192 - 65533
191 - 65533
190 - 65533
189 - 65533
188 - 65533
187 - 65533
186 - 65533
185 - 65533
184 - 65533
183 - 65533
182 - 65533
181 - 65533
180 - 65533
179 - 65533
178 - 65533
177 - 65533
176 - 65533
175 - 65533
174 - 65533
173 - 65533
172 - 65533
171 - 65533
170 - 65533
169 - 65533
168 - 65533
167 - 65533
166 - 65533
165 - 65533
164 - 65533
163 - 65533
162 - 65533
161 - 65533
160 - 65533
159 - 65533
158 - 65533
157 - 65533
156 - 65533
155 - 65533
154 - 65533
153 - 65533
152 - 65533
151 - 65533
150 - 65533
149 - 65533
148 - 65533
147 - 65533
146 - 65533
145 - 65533
144 - 65533
143 - 65533
142 - 65533
141 - 65533
140 - 65533
139 - 65533
138 - 65533
137 - 65533
136 - 65533
135 - 65533
134 - 65533
133 - 65533
132 - 65533
131 - 65533
130 - 65533
129 - 65533
128 - 65533
127 - 127
126 - 126
125 - 125
124 - 124
123 - 123
122 - 122
121 - 121
120 - 120
119 - 119
118 - 118
117 - 117
116 - 116
115 - 115
114 - 114
113 - 113
112 - 112
111 - 111
110 - 110
109 - 109
108 - 108
107 - 107
106 - 106
105 - 105
104 - 104
103 - 103
102 - 102
101 - 101
100 - 100
 99 - 99
 98 - 98
 97 - 97
 96 - 96
 95 - 95
 94 - 94
 93 - 93
 92 - 92
 91 - 91
 90 - 90
 89 - 89
 88 - 88
 87 - 87
 86 - 86
 85 - 85
 84 - 84
 83 - 83
 82 - 82
 81 - 81
 80 - 80
 79 - 79
 78 - 78
 77 - 77
 76 - 76
 75 - 75
 74 - 74
 73 - 73
 72 - 72
 71 - 71
 70 - 70
 69 - 69
 68 - 68
 67 - 67
 66 - 66
 65 - 65
 64 - 64
 63 - 63
 62 - 62
 61 - 61
 60 - 60
 59 - 59
 58 - 58
 57 - 57
 56 - 56
 55 - 55
 54 - 54
 53 - 53
 52 - 52
 51 - 51
 50 - 50
 49 - 49
 48 - 48
 47 - 47
 46 - 46
 45 - 45
 44 - 44
 43 - 43
 42 - 42
 41 - 41
 40 - 40
 39 - 39
 38 - 38
 37 - 37
 36 - 36
 35 - 35
 34 - 34
 33 - 33
 32 - 32
 31 - 31
 30 - 30
 29 - 29
 28 - 28
 27 - 27
 26 - 26
 25 - 25
 24 - 24
 23 - 23
 22 - 22
 21 - 21
 20 - 20
 19 - 19
 18 - 18
 17 - 17
 16 - 16
 15 - 15
 14 - 14
 13 - 13
 12 - 12
 11 - 11
 10 - 10
  9 - 9
  8 - 8
  7 - 7
  6 - 6
  5 - 5
  4 - 4
  3 - 3
  2 - 2
  1 - 1
  0 - 0
```

Or, the working variant:
```
perl v5.30.3
255 - 65533
254 - 65533
253 - 65533
252 - 65533
251 - 65533
250 - 65533
249 - 65533
248 - 65533
247 - 65533
246 - 65533
245 - 65533
244 - 65533
243 - 65533
242 - 65533
241 - 65533
240 - 65533
239 - 65533
238 - 65533
237 - 65533
236 - 65533
235 - 65533
234 - 65533
233 - 65533
232 - 65533
231 - 65533
230 - 65533
229 - 65533
228 - 65533
227 - 65533
226 - 65533
225 - 65533
224 - 65533
223 - 65533
222 - 65533
221 - 65533
220 - 65533
219 - 65533
218 - 65533
217 - 65533
216 - 65533
215 - 65533
214 - 65533
213 - 65533
212 - 65533
211 - 65533
210 - 65533
209 - 65533
208 - 65533
207 - 65533
206 - 65533
205 - 65533
204 - 65533
203 - 65533
202 - 65533
201 - 65533
200 - 65533
199 - 65533
198 - 65533
197 - 65533
196 - 65533
195 - 65533
194 - 65533
193 - 65533
192 - 65533
191 - 65533
190 - 65533
189 - 65533
188 - 65533
187 - 65533
186 - 65533
185 - 65533
184 - 65533
183 - 65533
182 - 65533
181 - 65533
180 - 65533
179 - 65533
178 - 65533
177 - 65533
176 - 65533
175 - 65533
174 - 65533
173 - 65533
172 - 65533
171 - 65533
170 - 65533
169 - 65533
168 - 65533
167 - 65533
166 - 65533
165 - 65533
164 - 65533
163 - 65533
162 - 65533
161 - 65533
160 - 65533
159 - 65533
158 - 65533
157 - 65533
156 - 65533
155 - 65533
154 - 65533
153 - 65533
152 - 65533
151 - 65533
150 - 65533
149 - 65533
148 - 65533
147 - 65533
146 - 65533
145 - 65533
144 - 65533
143 - 65533
142 - 65533
141 - 65533
140 - 65533
139 - 65533
138 - 65533
137 - 65533
136 - 65533
135 - 65533
134 - 65533
133 - 65533
132 - 65533
131 - 65533
130 - 65533
129 - 65533
128 - 65533
127 - 127
126 - 126
125 - 125
124 - 124
123 - 123
122 - 122
121 - 121
120 - 120
119 - 119
118 - 118
117 - 117
116 - 116
115 - 115
114 - 114
113 - 113
112 - 112
111 - 111
110 - 110
109 - 109
108 - 108
107 - 107
106 - 106
105 - 105
104 - 104
103 - 103
102 - 102
101 - 101
100 - 100
 99 - 99
 98 - 98
 97 - 97
 96 - 96
 95 - 95
 94 - 94
 93 - 93
 92 - 92
 91 - 91
 90 - 90
 89 - 89
 88 - 88
 87 - 87
 86 - 86
 85 - 85
 84 - 84
 83 - 83
 82 - 82
 81 - 81
 80 - 80
 79 - 79
 78 - 78
 77 - 77
 76 - 76
 75 - 75
 74 - 74
 73 - 73
 72 - 72
 71 - 71
 70 - 70
 69 - 69
 68 - 68
 67 - 67
 66 - 66
 65 - 65
 64 - 64
 63 - 63
 62 - 62
 61 - 61
 60 - 60
 59 - 59
 58 - 58
 57 - 57
 56 - 56
 55 - 55
 54 - 54
 53 - 53
 52 - 52
 51 - 51
 50 - 50
 49 - 49
 48 - 48
 47 - 47
 46 - 46
 45 - 45
 44 - 44
 43 - 43
 42 - 42
 41 - 41
 40 - 40
 39 - 39
 38 - 38
 37 - 37
 36 - 36
 35 - 35
 34 - 34
 33 - 33
 32 - 32
 31 - 31
 30 - 30
 29 - 29
 28 - 28
 27 - 27
 26 - 26
 25 - 25
 24 - 24
 23 - 23
 22 - 22
 21 - 21
 20 - 20
 19 - 19
 18 - 18
 17 - 17
 16 - 16
 15 - 15
 14 - 14
 13 - 13
 12 - 12
 11 - 11
 10 - 10
  9 - 9
  8 - 8
  7 - 7
  6 - 6
  5 - 5
  4 - 4
  3 - 3
  2 - 2
  1 - 1
  0 - 0
```

Not sure what really happens under the hood, but I guess this is not a PDF::API2 or PDF::Builder problem then, so sorry for the false alarm, I guess.

Best regards, Sven

**Comment by PhilterPaper** [comment]
Hi Sven,

All I get out of running your test code (Windows 10, Perl 5.32) is
```
C:\Users\Phil\Desktop>test205.pl
perl v5.32.1
Builder: 3.026

C:\Users\Phil\Desktop>
```
No warnings. I suspect that you either have a corrupted font file on this particular machine, or something strange going on in the overall environment. If you think it's something local, and not either PDF::API2 or PDF::Builder code, I'll go ahead and close this ticket.

By the way, concerning the line
```
my $font = $pdf->ttfont('DejaVuSansMono.ttf', '-encode', 'utf-8');
```
while that is allowable, the intent is for "encode" (you can give it with or without the leading - hyphen) to be a _hash_ element. Thus, the convention would be to write
```
my $font = $pdf->ttfont('DejaVuSansMono.ttf', 'encode' => 'utf-8');
```
It's easier to understand the code that way. Quotes around "encode" are generally optional, but often a good idea.

**Comment by PhilterPaper** [comment]
It sounds like you're satisfied with the results, so I'll go ahead and close this ticket.

**Comment by svenoe** [comment]
Yes, thanks for replying to me here, in the first place. :)

(Just for completeness though - no, it's not related to any of my fonts at all, it is, as written in my lengthy post, that `unpack('U*', decode('utf-8', pack('C*', 0..255)))` has a different (potentially wrong) result on my old testing server running a standard Ubuntu 18.04 with its perl 5.26.1, compared to newer systems. It's definitely not a problem of PDF::API2 or ::Builder, and as it only seems to affect some old version, at least for me I don't see any todo anymore.)
