### ISSUE TITLE
`PDF::Builder::default_page_boundaries` is bound to fail

### ISSUE THREAD

**Issue by sciurius** [PhilterPaper/Perl-PDF-Builder#219]
`PDF::Builder::Page::boundaries` can return a hash (`%boudaries`), a list (`@coordinates`) or an object (`$self`).

In `PDF::Builder::default_page_boundaries` it is called to return a hash **reference**.

**Comment by PhilterPaper** [comment]
Is this different from #210, or an incorrect fix made, or an incomplete update was made?

**Comment by sciurius** [comment]
I guess it is the result from an incorrect fix.
See https://github.com/ssimms/pdfapi2/pull/85/

**Comment by PhilterPaper** [comment]
I believe that I have it fixed, and have also updated the POD entries to make them consistent with the code.
