### ISSUE TITLE
Mention Text::PDF in the history lesson

### ISSUE THREAD

**Issue by cpansprout** [PhilterPaper/Perl-PDF-Builder#75]
I would suggest you mention that PDF::API2 was actually a fork of Text::PDF.  (If you care about such trivia.)

(These forks seem to breed like rabbits.  Forkitis. :-)

**Comment by PhilterPaper** [comment]
I do seem to vaguely recall reading something about Text::PDF->PDF::API[2], but I can't find it now. I hesitate to add it to the "history lesson" without an authoritative source to back it up. Text::PDF only goes back (on CPAN, anyway) to 2006, while PDF::API2 goes back to 2001. If you can point me to some documentation that PDF::API2 (or PDF::API) sprang from Text::PDF, I'll be happy to mention it. Were you involved with Text::PDF?

**Comment by cpansprout** [comment]
No, I was not involved in it.  I just noticed that some of the source code is identical.  Also, the oldest version of Text::PDF is actually from 1999 (see <http://backpan.perl.org/authors/id/M/MH/MHOSKEN/>).

And digging around backpan a bit more, I see that <http://backpan.perl.org/authors/id/A/AR/AREIBENS/PDF-API2-0.2.0.2_dev.tar.gz> includes a readme.txt that says:

```
This module is 'The Next Generation' of Text::PDF::API which initially 
provided a nice API around the Text::PDF::* modules created by Martin Hosken.
```
So it seems it was originally a wrapper around Text::PDF that eventually incorporated all of the latter’s functionality (some of it apparently by copy & paste).

**Comment by PhilterPaper** [comment]
OK, I have added this information to Builder.pm. Thanks for the Heads Up. It will be in the next release.

> So it seems it was originally a wrapper around Text::PDF that eventually incorporated all of the latter’s functionality (some of it apparently by copy & paste).

Hey, if you gotta steal, steal from the best! :) Actually, there's a lot of evidence for copy & paste in PDF::API2 -- several of us found several routines where the author had copied another routine's code, but failed to update some variables inside, resulting in bugs.

> (These forks seem to breed like rabbits. Forkitis. :-)

I wish I didn't have to make a fork -- I would have much rathered contributed to PDF::API2. However, Steve Simms is in the habit of simply discarding any submitted changes large enough that he can't be bothered to look through the code. That's a shame.
